version: '3'

services:
  postgres:
    image: postgres:16
    shm_size: '4gb'
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=myspot
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql

  # seq:
  #   image: datalust/seq 
  #   container_name: seq
  #   restart: unless-stopped
  #   environment:
  #     - ACCEPT_EULA=Y
  #   ports:
  #     - 5341:80

volumes:
  postgres:
    driver: local